{% set name = "kickscore" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2478196d824b26f81345e8669f3f8eb15eb8921c68ebab3e796dd17eec2a367

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - numba
    - numpy
    - scipy

test:
  imports:
    - kickscore
    - kickscore.fitter
    - kickscore.kernel
    - kickscore.observation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucasmaystre/kickscore
  summary: A dynamic skill rating system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
