{% set name = "kickscore" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08740b714c7c1d0edc856f81995720ab6161b5beb4d62732782605f3ac1d1d57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - numba
    - numpy
    - scipy

test:
  imports:
    - kickscore
    - kickscore.fitter
    - kickscore.kernel
    - kickscore.observation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucasmaystre/kickscore
  summary: A dynamic skill rating system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
